export const IOV_PROTOCOL_VOCABULARY = {
  valueCapture: {
    l1: "~ValueCaptureProtocol",
    l2: {
      timeSlice: "~~TimeSlice",
      activity: "~~Activity",
      proof: "~~Proof",
      attribution: "~~Attribution",
      integrity: "~~Integrity",
    },
    l3: {
      startTime: "~~~StartTime",
      endTime: "~~~EndTime",
      duration: "~~~Duration",
      activityLabel: "~~~ActivityLabel",
      taskType: "~~~TaskType",
      intent: "~~~Intent",
      proofOfActivity: "~~~ProofOfActivity",
      evidenceLink: "~~~EvidenceLink",
      artifactType: "~~~ArtifactType",
      community: "~~~Community",
      project: "~~~Project",
      contributorRole: "~~~ContributorRole",
      proofQuality: "~~~ProofQuality",
      anomalyFlag: "~~~AnomalyFlag",
      fraudRiskSignal: "~~~FraudRiskSignal",
    },
  },
  wellbeing: {
    l1: "~WellbeingProtocol",
    l2: {
      physiology: "~~Physiology",
      emotion: "~~Emotion",
      feeling: "~~Feeling",
      thought: "~~Thought",
      habit: "~~Habit",
      performance: "~~Performance",
    },
    l3: {
      movement: "~~~Movement",
      rest: "~~~Rest",
      diet: "~~~Diet",
      fasting: "~~~Fasting",
      breathwork: "~~~Breathwork",
      biomarkers: "~~~Biomarkers",
      bodyComposition: "~~~BodyComposition",
      dominantFeeling: "~~~DominantFeeling",
      cognitiveState: "~~~CognitiveState",
      thinkingSystem: "~~~ThinkingSystem",
      mentalModel: "~~~MentalModel",
      cognitiveBias: "~~~CognitiveBias",
      consciousness: "~~~Consciousness",
      cue: "~~~Cue",
      routine: "~~~Routine",
      reward: "~~~Reward",
      consistency: "~~~Consistency",
      streak: "~~~Streak",
      learningOutput: "~~~LearningOutput",
      earningOutput: "~~~EarningOutput",
      orgBuildingOutput: "~~~OrgBuildingOutput",
      skillApplication: "~~~SkillApplication",
      communityContext: "~~~CommunityContext",
    },
  },
  saocommons: {
    l1: "~SAOcommons",
    l2: {
      learning: "~~Learning",
      earning: "~~Earning",
      orgBuilding: "~~OrgBuilding",
      validation: "~~Validation",
      attestation: "~~Attestation",
      valuation: "~~Valuation",
      disputeResolution: "~~DisputeResolution",
    },
    l3: {
      learningTask: "~~~LearningTask",
      learningOutcome: "~~~LearningOutcome",
      learningEvidence: "~~~LearningEvidence",
      earningTask: "~~~EarningTask",
      earningOutcome: "~~~EarningOutcome",
      earningEvidence: "~~~EarningEvidence",
      orgTask: "~~~OrgTask",
      orgOutcome: "~~~OrgOutcome",
      orgEvidence: "~~~OrgEvidence",
      evidenceReview: "~~~EvidenceReview",
      reviewerSet: "~~~ReviewerSet",
      validationDecision: "~~~ValidationDecision",
      skillLevelBefore: "~~~SkillLevelBefore",
      skillLevelAfter: "~~~SkillLevelAfter",
      attestationRecord: "~~~AttestationRecord",
      valueCredit: "~~~ValueCredit",
      equityWeight: "~~~EquityWeight",
      distributionRule: "~~~DistributionRule",
      disputeCase: "~~~DisputeCase",
      appeal: "~~~Appeal",
      finalDecision: "~~~FinalDecision",
    },
  },
} as const;

export type IovProtocolVocabulary = typeof IOV_PROTOCOL_VOCABULARY;
